Bloggie.Web/Controllers/AdminBlogPostsController.cs
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Bloggie.Web.Controllers
{
    public class AdminBlogPostsController : Controller
    {
        private readonly ITagRepository _tagRepository;
        private readonly IBlogPostRepository _blogPostRepository;

        //Constructor Injection
        public AdminBlogPostsController(ITagRepository tagRepository ,IBlogPostRepository blogPostRepository)
        {
            _tagRepository = tagRepository;
            _blogPostRepository = blogPostRepository;
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        
        public async Task<IActionResult> Add() 
        {
            //Saray tags agaye yahan se repository le ayi database se hamare liye ye
            var tags = await _tagRepository.GetAllAsync();

            var model = new AddBlogPostRequest()
            {
                //Always take string value in linq

                Tags = tags.Select(x => new SelectListItem { Text = x.DisplayName , Value = x.Id.ToString()})

            };

            return View(model);
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {
            //Map the view model to domain model a good practice

            var blogPost = new BlogPost()
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible,

            };

            //Map Tags from selected tags crucial step iterate through all the selected tags we want to save in database.
            var selectedTags = new List<Tag>();

            foreach (var selectedTagId in addBlogPostRequest.SelectedTags)
            {
                //Basically jo tags humne select krke rkhe the na woh save tu id ki form mai hi horhe the tu
                //hamai ziada kuch krna nhi pra bas un arrat of strings ko guid banane ki koshish jri hai aur unki wohi id
                //se hum database se unhe uthane kis koshish krrhe

                var selectedTagAsGuid = Guid.Parse(selectedTagId);
                var existing = await _tagRepository.GetAsync(selectedTagAsGuid);
                
                if (existing != null)
                {
                    selectedTags.Add(existing);   
                }  
            }

            //Dalgye yahan pe saray selected tags asli walay domain model mai allah ka shukr
            blogPost.Tags = selectedTags; 

            await _blogPostRepository.AddAsync(blogPost);

            return RedirectToAction("Add");
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public async Task<IActionResult> List()
        {

            //Call the repository to get all the blogpost

            var blogPosts = await _blogPostRepository.GetAllAsync();
            
            return View(blogPosts);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)
        {
            // Retrieve the result from the repository
            var blogPost = await _blogPostRepository.GetAsync(Id);

            //Saaray tags dobara mangwao kyun ke edit krte waqt na janay kis tag ki zaroorat par jaye
            var tags = await _tagRepository.GetAllAsync();

            if(blogPost != null)
            {
                //Mapping domain mdel to view model and pass that model to view
                var editBlogPostRequest = new EditBlogPostRequest()
                {
                    Id = blogPost.Id,
                    Heading = blogPost.Heading,
                    PageTitle = blogPost.PageTitle,
                    Content = blogPost.Content,
                    ShortDescription = blogPost.ShortDescription,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    UrlHandle = blogPost.UrlHandle,
                    PublishedDate = blogPost.PublishedDate,
                    Author = blogPost.Author,
                    Visible = blogPost.Visible,
                    //Saaray tags dobara mangwao kyun ke edit krte waqt na janay kis tag ki zaroorat par jaye
                    Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }),

                    //Konse tags selected the ye sirf user ko batana hai it is not a necessary step
                    SelectedTags = blogPost.Tags.Select(x => x.Id.ToString()).ToArray()
                };
                return View(editBlogPostRequest);
            }
            else
            {
                return View(null);
            }
        }

        [Authorize(Roles = "Admin")]
        //Method overloading. It is an HTTP POST method.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            //Map view model to domain model again after done editing
            var blogPostDomainModel = new BlogPost()
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                Content = editBlogPostRequest.Content,
                PageTitle = editBlogPostRequest.PageTitle,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                UrlHandle = editBlogPostRequest.UrlHandle,
                PublishedDate = editBlogPostRequest.PublishedDate,
                Author = editBlogPostRequest.Author,
                Visible = editBlogPostRequest.Visible
            };

            //Map Tags from selected tags crucial step iterate through all the selected tags we want to save in database.
            var selectedTags = new List<Tag>();

            foreach (var selectedTagsinBlogPost in editBlogPostRequest.SelectedTags)
            {
                //Parse into Guid because it comes in the value which is in string

                var selectedTagAsGuid = Guid.Parse(selectedTagsinBlogPost);

                var existing = await _tagRepository.GetAsync(selectedTagAsGuid);

                if (existing != null)
                {
                    selectedTags.Add(existing);
                }
            }

            blogPostDomainModel.Tags = selectedTags;

            var addedinBlogPost = await _blogPostRepository.UpdateAsync(blogPostDomainModel);

            if(addedinBlogPost != null)
            {
                return RedirectToAction("Edit", new {id = editBlogPostRequest.Id});
            }
            else
            {
                return RedirectToAction("Edit", new { id = editBlogPostRequest.Id });
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            var founded = await _blogPostRepository.DeleteAsync(editBlogPostRequest.Id);

            if(founded != null)
            {
                //Show success notification
                return RedirectToAction("List");
            }
            else
            {
                //Show failure notification
                return RedirectToAction("Edit", new { id = editBlogPostRequest.Id });
            }
        } 
    }
}

Bloggie.Web/Controllers/AdminTagsController.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bloggie.Web.Controllers
{
    public class AdminTagsController : Controller
    {
        private readonly ITagRepository _tagRepository;

        //Constructor Injection
        public AdminTagsController(ITagRepository tagRepository)
        {
            _tagRepository = tagRepository;
        }

        //Block the access to other users give only to SuperAdmin
        [Authorize(Roles = "User")]       
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        [ActionName("Add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            ValidateAddTagRequest(addTagRequest);
            if(ModelState.IsValid == false)
            {
                return View();
            }
            //Model Binding
            // var name = addTagRequest.Name;
            // var displayName = addTagRequest.DisplayName;

            //Mapping AddTagRequest to Tag domain Model
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            }; 

            //Job of a repository to save changes to database not controller
            await _tagRepository.AddAsync(tag);

            return RedirectToAction("List");
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        //Name of the method is the action name itself
        [ActionName("List")]
        public async Task<IActionResult> List()
        {
            // Use Dbcontext to read the tags
            var tags = await _tagRepository.GetAllAsync();

            return View(tags);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await _tagRepository.GetAsync(id);

            if(tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName =  tag.DisplayName
                };

                return View(editTagRequest);
            }
            return View(null);
        }

        [Authorize(Roles = "Admin")]
        //Method overloading. It is an HTTP POST method.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            //Again using Model Binding to save changes in the database using dbcontext class. Simply converting view models into domain models

            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

            var updatedTag = await _tagRepository.UpdateAsync(tag);

            if(updatedTag != null)
            {
                //Show Success Notification
                //This is the way to pass parameter to the function when called in view like passing the object
                return RedirectToAction("Edit", new { id = editTagRequest.Id });
            }
            else
            {
                //Show Failure Notification
                return RedirectToAction("Edit", new { id = editTagRequest.Id });
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {

            var deletedTag = await _tagRepository.DeleteAsync(editTagRequest.Id);

            if(deletedTag != null)
            {                
                //Show success notification
                return RedirectToAction("List");
            }
            else
            {
                //Show failure notification
                return RedirectToAction("Edit", new { id = editTagRequest.Id });
            }
        }
        private void ValidateAddTagRequest(AddTagRequest addTagRequest)
        {
            if(addTagRequest.Name is not null && addTagRequest.DisplayName != null)
            {
                if(addTagRequest.Name == addTagRequest.DisplayName)
                {
                    ModelState.AddModelError("DisplayName", "Name cannot be the same as DisplayName");
                }
            }
        }
    }
}

Bloggie.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager
@using Microsoft.AspNetCore.Authorization;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bloggie.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bloggie.Web.styles.css" asp-append-version="true" />
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mt-3 mb-3">
            <div class="container">
                <div class="fw-bold">
                    <a class="navbar-brand" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                        asp-area=""
                        asp-controller="Home"
                        asp-action="Index">
                        Bloggie.Web
                    </a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                            @if(signInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                                       asp-area=""
                                       asp-controller="AdminTags"
                                       asp-action="Add">
                                        Add Tag
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                                       asp-area=""
                                       asp-controller="AdminTags"
                                       asp-action="List">
                                        Display Tags
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                                       asp-area=""
                                       asp-controller="AdminBlogPosts"
                                       asp-action="Add">
                                        Add BlogPost
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                                       asp-area=""
                                       asp-controller="AdminBlogPosts"
                                       asp-action="List">
                                        Display BlogPosts
                                    </a>
                                </li>

                                <li class="nav-item">
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <a class="nav-link" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                                            asp-area=""
                                            asp-controller="AdminUsers"
                                            asp-action="List">Display All Users
                                        </a>
                                    }
                                </li>
                            }
                    </ul>

                    <div class="d-flex align-items-center">
                        <!-- Jo bhi user currently logged in hai woh batadega ye method -->
                        <!-- Claim leta hai ye User ke jo user chalrha hai woh User object mai ajayega na ya nhi-->
                        @if(signInManager.IsSignedIn(User))
                        {
                            <div class="me-3 text-light">
                                <!-- Ye question mark not null ke hain user agr null na ho tu uski
                                identity jo null na ho tu usse name nikala hai -->
                                @User?.Identity?.Name
                            </div>

                            <a class="btn bg-light" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                                asp-area="" asp-controller="Account" asp-action="Logout">LogOut</a>
                        }
                        else
                        {
                            <a class="me-3 btn bg-light" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                            asp-area="" asp-controller="Account" asp-action="Register">Register</a>

                            <a class="btn bg-light" onMouseOver="this.style.color='#000'" onMouseOut="this.style.color='gray'"
                            asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        }
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Bloggie.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>